### ISSUE TITLE
TextEditorView.getPane is deprecated.

### ISSUE THREAD

**Issue by nibushibu** [tony612/highlight-column#17]
Use TextEditorView::getPaneView() instead
```
TextEditorView.getPane (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-view.js:279:7)
<unknown> (/Users/nibushibu/.atom/packages/highlight-column/lib/highlight-column-view.coffee:15:44)
atom-workspace.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-view.js:97:22)
atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:110:34)
atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
```

**Comment by tony612** [comment]
What's your version of this package? Maybe you should update it

**Comment by nibushibu** [comment]
Thank you for your reply and information.
My package version is 0.3.2. ( yes, It is not latest version..)

I tried to reinstall package (uninstall -> restart -> install) but there is error message as below.

> Version 0.3.2 is not the latest version available for this package, but it's the latest that is compatible with your version of Atom.

![150521-0001](https://cloud.githubusercontent.com/assets/399949/7750687/8ee1d0fe-0010-11e5-9784-fc0cd0d3e40b.png)

My Atom version is 0.200.0

Thank you.

お返事、どうもありがとうございます。

**Comment by tony612** [comment]
It's werid. I use atom 0.200.0, and it works. Try to uninstall and install again?

**Comment by tony612** [comment]
@nibushibu Just published a patch version, try to update it please :)

**Comment by nibushibu** [comment]
Thank you for the quick action!
I successed to update, then all error message (Deprecated calls) disappeared. :) :+1:
