### ISSUE TITLE
Doesn't appear to display on Atom 208

### ISSUE THREAD

**Issue by JohnMurga** [tony612/highlight-column#19]
Other similar packages have the same issue with 208 ...
Displays fine on 207, does not show on 208

**Comment by tony612** [comment]
@JohnMurga Thanks for your report. I found this today, also. I'll look into this these days

**Comment by JohnMurga** [comment]
I filed a report with Atom also as the underlayer doesn't show for other packages too

**Comment by JohnMurga** [comment]
And I got a response that may be useful ...
https://github.com/atom/atom/issues/7204#event-327883949

**Comment by tony612** [comment]
@JohnMurga Thanks! I think I know what's the problem probably

**Comment by tony612** [comment]
update to the latest version, it'll be fine(maybe you need to restart atom)
