### ISSUE TITLE
No longer functions after 0.5.2 update

### ISSUE THREAD

**Issue by mattge** [tony612/highlight-column#30]
I'm not sure when it happened but I recently updated my Atom packages and I notice now that highlight-column no longer functions. There is no error, restarting Atom doesn't help and disabling then enabling the highlight-column package has no effect. Running latest Atom 1.12.7

**Comment by Voronenko** [comment]
Confirm && vote up. Very useful handy plugin - would be cool to fix

**Comment by dodekeract** [comment]
Works for me.

Atom: 1.13.1 x64
OS: macOS Sierra 10.12.1
Highlight-Column: 0.5.2

**Comment by Voronenko** [comment]
Issues on :

Linux:  1.13.1 x64
OS: ubuntu 16.04.5 LTS
Highlight-Column: 0.5.2

**Comment by tony612** [comment]
Weird, it works for me. My env is:

Atom: 1.13.1 & 1.14.0-beta2
OS: macOS Sierra 10.12.2
Highlight-Column: 0.5.2

@mattge What's your env?

**Comment by mattge** [comment]
Atom: 1.12.7
OS: macOS 10.11.6 El Capitan
Highlight-column: 0.5.2

**Comment by chikamichi** [comment]
Confirmed with:

Atom: 1.11.0-beta5
OS: Linux XXX 4.8.0-34-generic #36-Ubuntu SMP Wed Dec 21 17:24:18 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Highlight-column: 0.5.2

**Comment by wbray** [comment]
Chiming in to say it doesn't work for me either, which is a shame as it's an especially helpful package when working with HAML.

Atom: 1.10.2
OS: Linux Ubuntu 16.04 LTS
Highlight Column: 0.5.2
