### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by deanshelton913** [tony612/highlight-column#5]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Function.module.exports.HighlightColumnView.activate (/Users/deanshelton/.atom/packages/highlight-column/lib/highlight-column-view.coffee:14:9)
```

**Comment by tony612** [comment]
@deanshelton913 Please update it to newest version(0.4.0) https://atom.io/packages/highlight-column
